# Generated by Django 2.1.3 on 2018-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='f_nacimiento',
            field=models.DateField(),
        ),
    ]
