# Generated by Django 2.1.3 on 2018-12-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(upload_to='media/perfil'),
        ),
    ]
