# Generated by Django 2.1.3 on 2018-12-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181206_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/perfil'),
        ),
    ]
