# Generated by Django 2.1.2 on 2018-12-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_perfil_seguidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='seguidores',
            field=models.ManyToManyField(null=True, related_name='_perfil_seguidores_+', to='users.Perfil'),
        ),
    ]
