# Generated by Django 2.1.2 on 2018-12-12 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181212_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='seguidores',
        ),
        migrations.AddField(
            model_name='perfil',
            name='seguidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Perfil'),
        ),
    ]
