# Generated by Django 2.1.3 on 2018-12-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181116_1657'),
        ('feed', '0002_remove_post_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tweet',
        ),
    ]
